default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: notifilter_development

test:
  <<: *default
  database: notifilter_test

production:
  <<: *default
  host: <%= ENV['NOTIFILTER_DBHOST'] %>
  username: <%= ENV['NOTIFILTER_DBUSER'] %>
  password: <%= ENV['NOTIFILTER_DBPASSWORD'] %>
  database: notifilter_production
  reconnect: true
