default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: notifilter_development

test:
  <<: *default
  database: notifilter_test

production:
  <<: *default
  username: <%= ENV['NOTIFILTER_DBHOST'] %>
  host: <%= ENV['NOTIFILTER_DBNAME'] %>
  password: <%= ENV['NOTIFILTER_DBPASSWORD'] %>
  reconnect: true
